# -*- coding: utf-8 -*-
"""CV matcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GvdXPc5Qtd-y90euA15Frflxwl3UxLmF
"""

# ============================================================
# CELL 1: IMPORTS & SETUP
# CV Matcher - AI Pipeline (Production Ready)
# ============================================================

# Install dependencies
#pip install sentence-transformers scikit-learn pandas numpy pdfplumber tqdm nltk -q

import os
import re
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Tuple, Optional

import numpy as np
import pandas as pd
import pdfplumber

import nltk
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm

nltk.download('punkt',    quiet=True)
nltk.download('stopwords', quiet=True)

print("✅ Imports ready!")

# ============================================================
# CELL 2: CONFIG & CONSTANTS
# ============================================================

# ── Model Configuration ──────────────────────────────────────
CONFIG = {
    'model_name': 'paraphrase-multilingual-MiniLM-L12-v2',
    'sections':   ['summary', 'education', 'skills', 'experience',
                   'certifications', 'projects', 'achievements'],
    'language':   'multilingual',
}

# ── Section Heading Keywords (EN + ID) ───────────────────────
# Digunakan oleh is_heading_line() untuk mendeteksi section CV
SECTION_KEYWORDS = {
    'summary': {
        'en': ['professional summary', 'profile', 'about me',
                'career objective', 'summary'],
        'id': ['ringkasan profesional', 'profil', 'tentang saya',
                'ringkasan', 'tujuan karir']
    },
    'education': {
        'en': ['education', 'educational background',
                'academic background', 'education history'],
        'id': ['pendidikan', 'riwayat pendidikan',
                'latar belakang pendidikan']
    },
    'skills': {
        'en': ['skills', 'technical skills', 'core skills', 'key skills',
                'tools', 'technologies', 'competencies'],
        'id': ['keahlian', 'skill', 'kompetensi inti', 'tools',
                'teknologi', 'kemampuan teknis']
    },
    'experience': {
        'en': ['work experience', 'professional experience',
                'employment history', 'career history',
                'internship experience', 'experience'],
        'id': ['pengalaman kerja', 'pengalaman profesional',
                'riwayat pekerjaan', 'riwayat karir', 'pengalaman magang']
    },
    'certifications': {
        'en': ['certifications', 'certificates', 'credentials',
                'licenses', 'training', 'certification'],
        'id': ['sertifikasi', 'sertifikat', 'kredensial',
                'lisensi', 'pelatihan']
    },
    'projects': {
        'en': ['projects', 'project experience', 'academic projects',
                'personal projects', 'portfolio', 'key projects'],
        'id': ['proyek', 'pengalaman proyek', 'proyek akademik',
                'proyek personal', 'portofolio', 'proyek utama']
    },
    'achievements': {
        'en': ['achievements', 'accomplishments', 'awards',
                'recognitions', 'honors', 'awards and honors'],
        'id': ['pencapaian', 'prestasi', 'penghargaan',
                'pengakuan', 'award', 'penghargaan dan prestasi']
    },
}

# ── Section Weights (Base — di-override oleh dynamic weighting) ──
# Digunakan sebagai fallback jika dynamic weighting tidak dipanggil
SECTION_WEIGHTS_BASE = {
    'experience':     0.40,
    'skills':         0.30,
    'summary':        0.15,
    'education':      0.10,
    'certifications': 0.05,
    'projects':       0.00,
    'achievements':   0.00,
}

# ── Match Label Thresholds ────────────────────────────────────
MATCH_THRESHOLDS = {
    'strong':    58.0,   # >= 58%  → Strong Match
    'potential': 38.0,   # 38–57% → Potential Match
                         # < 38%  → Low Match
}

MATCH_LABELS = {
    'strong':    ('Strong Match',    '🟢'),
    'potential': ('Potential Match', '🟡'),
    'low':       ('Low Match',       '🔴'),
}

print("✅ Config & constants loaded!")
print(f"   Model    : {CONFIG['model_name']}")
print(f"   Sections : {', '.join(CONFIG['sections'])}")
# ============================================================
# CELL 3: TEXT PROCESSING
#   3A — Text Normalization
#   3B — Section Extraction (Heading-Aware)
#   3C — PDF & CSV Extractor
# ============================================================

# ============================================================
# CELL 3: TEXT PROCESSING
#   3A — Text Normalization
#   3B — Section Extraction (Heading-Aware)
#   3C — PDF & CSV Extractor
# ============================================================


# ── 3A: TEXT NORMALIZATION ───────────────────────────────────

def normalize_text(text: str, aggressive: bool = False) -> str:
    """
    Normalisasi teks untuk preprocessing.

    Args:
        text       : input teks
        aggressive : True  → hapus special chars (untuk keyword extraction)
                     False → pertahankan tanda baca (untuk SBERT)
    Returns:
        str: teks yang sudah dinormalisasi
    """
    if not text:
        return ""

    text = text.replace("\n", " ").replace("\r", " ")

    if aggressive:
        text = re.sub(r"[^a-zA-Z0-9\s\+\#\.\/\-]", " ", text)
    else:
        text = re.sub(r"[^\w\s\.\,\-\(\)\+\#\/]", " ", text)

    return re.sub(r"\s+", " ", text).strip()


def clean_text_for_sbert(text: str) -> str:
    """Gentle normalization — pertahankan makna semantik untuk SBERT."""
    return normalize_text(text, aggressive=False)


# ── 3B: SECTION EXTRACTION ───────────────────────────────────

def is_heading_line(line: str, section_keywords: Dict) -> Tuple[bool, Optional[str]]:
    """
    Deteksi apakah sebuah baris adalah heading section CV.

    Format yang didukung:
        - Uppercase  : "PROFESSIONAL SUMMARY"
        - Lowercase  : "professional summary"
        - Title Case : "Professional Summary"
        - Bernomor   : "1. Education" atau "2) Work Experience"
        - Berkolon   : "Skills:" atau "Experience:"

    Diabaikan (bukan heading):
        - Bullet point : "- Python" atau "• Developed..."
        - Teks panjang : > 80 karakter
        - Terlalu banyak kata : > 6 kata
        - Tidak cocok keyword manapun

    Args:
        line            : satu baris teks dari CV
        section_keywords: SECTION_KEYWORDS dict

    Returns:
        Tuple (is_heading: bool, matched_section: str | None)
    """
    line = line.strip()

    if not line or len(line) < 3:
        return False, None

    if line[0] in ('-', '•', '*'):
        return False, None

    if len(line) > 80:
        return False, None

    # Normalisasi: hapus trailing colon & numbering
    line_clean = re.sub(r'^(\d+[\.\)])\s+', '', line.rstrip(':')).strip()

    if len(line_clean.split()) > 6:
        return False, None

    line_lower = line_clean.lower()

    for section_name, keywords in section_keywords.items():
        all_keywords = keywords['en'] + keywords['id']
        for kw in sorted(all_keywords, key=len, reverse=True):
            if re.search(r'\b' + re.escape(kw) + r'\b', line_lower):
                return True, section_name

    return False, None


def extract_cv_sections(cv_text: str) -> Dict[str, str]:
    """
    Ekstrak section CV berdasarkan deteksi heading per baris.

    Algoritma:
        1. Split teks jadi baris
        2. Tiap baris dicek: heading atau konten?
        3. Konten dikumpulkan ke section yang aktif
        4. Heading baru = simpan section lama, mulai section baru
        5. Setiap section di-clean untuk SBERT

    Args:
        cv_text: full teks CV

    Returns:
        Dict[section_name: cleaned_section_text]
        Section kosong → string kosong ""
    """
    sections = {s: "" for s in CONFIG['sections']}
    current_section = None
    buffer = []

    for line in cv_text.split('\n'):
        is_heading, matched = is_heading_line(line, SECTION_KEYWORDS)

        if is_heading:
            if current_section is not None:
                sections[current_section] = '\n'.join(buffer).strip()
            current_section = matched
            buffer = []
        else:
            if current_section is not None:
                buffer.append(line)

    # Simpan section terakhir
    if current_section is not None:
        sections[current_section] = '\n'.join(buffer).strip()

    # Clean tiap section untuk SBERT
    return {k: clean_text_for_sbert(v) for k, v in sections.items()}


# ── 3C: PDF & CSV EXTRACTOR ──────────────────────────────────

def _fix_encoding(text: str) -> str:
    """
    Perbaiki encoding error umum pada teks hasil ekstraksi PDF/CSV.

    Karakter yang diperbaiki:
        â¢  → •    (bullet point)
        â€™ → '    (apostrophe)
        â€" → –    (en dash)
        â€œ → "    (open quote)
        â€  → "    (close quote)
    """
    if not text:
        return ""

    try:
        text = text.encode('latin-1').decode('utf-8')
    except (UnicodeEncodeError, UnicodeDecodeError):
        pass

    fixes = {
        'â¢': '•', 'â€™': "'", 'â€˜': "'",
        'â€œ': '"', 'â€': '"',  'â€"': '–',
        'â€"': '—', 'Ã©': 'é',  'Ã¨': 'è',
        '\x00': '',  '\uf0b7': '•',
    }
    for wrong, correct in fixes.items():
        text = text.replace(wrong, correct)

    return text


def extract_text_from_pdf(pdf_path: str) -> str:
    """
    Ekstrak teks dari file PDF menggunakan pdfplumber.

    Args:
        pdf_path: path ke file PDF

    Returns:
        str: teks hasil ekstraksi, "" jika gagal atau file tidak ditemukan

    Catatan:
        PDF berbasis gambar (scan) tidak bisa diekstrak dengan metode ini.
        PDF 2 kolom mungkin menghasilkan urutan teks yang tidak sempurna.
    """
    path = Path(pdf_path)
    if not path.exists():
        print(f"  ⚠️  File tidak ditemukan: {pdf_path}")
        return ""

    try:
        pages = []
        with pdfplumber.open(path) as pdf:
            for i, page in enumerate(pdf.pages):
                text = page.extract_text()
                if text:
                    pages.append(text)
                else:
                    print(f"  ⚠️  Halaman {i+1} kosong (mungkin berbasis gambar)")

        if not pages:
            print(f"  ❌ Tidak ada teks yang berhasil diekstrak: {pdf_path}")
            return ""

        combined = '\n'.join(pages)
        combined = _fix_encoding(combined)
        combined = re.sub(r'\n{3,}', '\n\n', combined)
        combined = re.sub(r'[ \t]+', ' ', combined)
        return combined.strip()

    except Exception as e:
        print(f"  ❌ Error membaca PDF {pdf_path}: {e}")
        return ""


def extract_text_from_csv_row(resume_text: str) -> str:
    """
    Clean teks resume dari kolom dataset CSV (misal Kaggle Resume Dataset).

    Args:
        resume_text: teks mentah dari kolom 'Resume'

    Returns:
        str: teks yang sudah bersih
    """
    if not resume_text or not isinstance(resume_text, str):
        return ""

    text = _fix_encoding(resume_text)
    text = re.sub(r'\r\n|\r', '\n', text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    text = re.sub(r'[ \t]+', ' ', text)
    return text.strip()


def load_cv(input_data: str, source: str = 'auto') -> str:
    """
    Universal CV loader — deteksi otomatis PDF vs teks biasa.

    Args:
        input_data : path ke PDF, atau teks CV langsung
        source     : 'pdf', 'text', atau 'auto' (default)

    Returns:
        str: teks CV yang sudah bersih dan siap diproses
    """
    if source == 'auto':
        source = 'pdf' if isinstance(input_data, str) and \
                          input_data.lower().endswith('.pdf') else 'text'

    return extract_text_from_pdf(input_data) if source == 'pdf' \
        else extract_text_from_csv_row(input_data)


print("✅ Text processing ready!")
print("   3A — normalize_text(), clean_text_for_sbert()")
print("   3B — is_heading_line(), extract_cv_sections()")
print("   3C — extract_text_from_pdf(), load_cv()")

# ============================================================
# CELL 4: SBERT ENCODER + DYNAMIC WEIGHTING
#   4A — SBERT Encoder
#   4B — Dynamic Weighting (JD-aware)
# ============================================================


# ── 4A: SBERT ENCODER ────────────────────────────────────────

print("⏳ Loading SBERT model...")
_sbert_model = SentenceTransformer(CONFIG['model_name'])
print(f"✅ SBERT model loaded: {CONFIG['model_name']}")


def encode_text(text: str) -> Optional[np.ndarray]:
    """
    Encode satu teks ke vector SBERT (384 dimensi).

    Args:
        text: teks yang akan di-encode

    Returns:
        np.ndarray shape (384,), atau None jika teks terlalu pendek
    """
    if not text or len(text.strip()) < 5:
        return None
    return _sbert_model.encode(clean_text_for_sbert(text), convert_to_numpy=True)


def encode_sections(cv_sections: Dict[str, str]) -> Dict[str, Optional[np.ndarray]]:
    """
    Encode semua section CV ke vector SBERT.

    Args:
        cv_sections: Dict hasil extract_cv_sections()

    Returns:
        Dict[section_name: embedding | None jika section kosong]
    """
    return {
        name: encode_text(text) if text and len(text.strip()) > 5 else None
        for name, text in cv_sections.items()
    }


def encode_jd(jd_text: str) -> np.ndarray:
    """
    Encode full teks JD ke satu vector SBERT.

    JD di-encode sebagai satu unit karena strukturnya tidak
    sekonsisten CV — lebih aman encode keseluruhan JD.

    Args:
        jd_text: full teks job description

    Returns:
        np.ndarray shape (384,)
    """
    return _sbert_model.encode(clean_text_for_sbert(jd_text), convert_to_numpy=True)


def section_similarity(
    cv_embedding: Optional[np.ndarray],
    jd_embedding: np.ndarray
) -> float:
    """
    Hitung cosine similarity antara satu section CV dengan JD.

    Args:
        cv_embedding : embedding section CV (None jika section kosong)
        jd_embedding : embedding JD

    Returns:
        float: similarity 0.0–1.0
               0.0 jika section CV kosong
    """
    if cv_embedding is None:
        return 0.0
    sim = cosine_similarity(
        cv_embedding.reshape(1, -1),
        jd_embedding.reshape(1, -1)
    )[0][0]
    return float(np.clip(sim, 0.0, 1.0))


# ── 4B: DYNAMIC WEIGHTING ────────────────────────────────────

def _detect_jd_signals(jd_text: str) -> Dict[str, float]:
    """
    Deteksi sinyal eksplisit per section dari teks JD.

    Setiap section punya set sinyal (kata/frasa kunci) yang
    menandakan section tersebut diprioritaskan di JD ini.

    Returns:
        Dict[section_name: signal_strength 0.0–1.0]
    """
    t = jd_text.lower()

    signals = {
        'experience': min(1.0, sum([
            bool(re.search(
                r'\d+\+?\s*(?:years?|yrs?|tahun)\s+(?:of\s+)?(?:experience|pengalaman)', t)),
            bool(re.search(
                r'(?:minimum|at least|minimal|setidaknya)\s+\d+\s*(?:years?|tahun)', t)),
            any(w in t for w in ['work experience', 'professional experience',
                                  'pengalaman kerja', 'track record', 'experienced in']),
            any(w in t for w in ['experience required', 'experienced candidate']),
        ]) * 0.35),

        'skills': min(1.0, sum([
            any(w in t for w in ['skills', 'proficiency', 'proficient', 'expertise',
                                  'keahlian', 'kemampuan', 'kompetensi']),
            any(w in t for w in ['required skills', 'technical skills', 'must have']),
            any(w in t for w in ['familiar with', 'knowledge of', 'experience with']),
            bool(re.search(r'\b(?:python|java|sql|aws|excel|sap|javascript)\b', t)),
        ]) * 0.28),

        'education': min(1.0, sum([
            any(w in t for w in ['bachelor', 'master', 'phd', 'degree', 'diploma',
                                  'sarjana', 'magister', 's1', 's2']),
            any(w in t for w in ['education required', 'educational background',
                                  'latar belakang pendidikan']),
            any(w in t for w in ['computer science', 'engineering', 'accounting',
                                  'teknik informatika', 'statistics', 'mathematics']),
            bool(re.search(r'(?:degree|diploma)\s+in\b', t)),
        ]) * 0.27),

        'summary': min(1.0, 0.3 + sum([
            any(w in t for w in ['leadership', 'communication', 'teamwork',
                                  'analytical', 'problem solving', 'kepemimpinan']),
            any(w in t for w in ['passionate', 'motivated', 'proactive', 'fast learner']),
            any(w in t for w in ['strong background', 'proven track', 'demonstrated ability']),
        ]) * 0.15),

        'certifications': min(1.0, sum([
            any(w in t for w in ['certified', 'certification', 'certificate',
                                  'sertifikat', 'sertifikasi', 'lisensi']),
            any(w in t for w in ['cpa', 'aws certified', 'pmp', 'cissp', 'cfa']),
            bool(re.search(r'(?:certification|certificate)\s+(?:required|preferred|is a plus)', t)),
        ]) * 0.35),

        'projects':     0.0,
        'achievements': 0.0,
    }

    return signals


def compute_dynamic_weights(jd_text: str, verbose: bool = False) -> Dict[str, float]:
    """
    Hitung bobot section secara dinamis berdasarkan konten JD.

    Semakin eksplisit sebuah section disebutkan di JD,
    semakin tinggi bobotnya. Total bobot selalu = 1.0.

    Hard caps per section:
        experience    : 25% – 55%
        skills        : 20% – 45%
        summary       :  5% – 20%
        education     :  3% – 20%
        certifications:  0% – 15%
        projects      :  0%  (tidak di-score)
        achievements  :  0%  (tidak di-score)

    Args:
        jd_text : full teks JD
        verbose : print detail perhitungan weights

    Returns:
        Dict[section_name: weight] dengan total = 1.0
    """
    BASE = {
        'experience': 0.35, 'skills': 0.28, 'summary': 0.12,
        'education':  0.08, 'certifications': 0.02,
        'projects':   0.00, 'achievements':   0.00,
    }
    CAPS = {
        'experience':     (0.25, 0.55),
        'skills':         (0.20, 0.45),
        'summary':        (0.05, 0.20),
        'education':      (0.03, 0.20),
        'certifications': (0.00, 0.15),
        'projects':       (0.00, 0.00),
        'achievements':   (0.00, 0.00),
    }

    signals = _detect_jd_signals(jd_text)

    # Base + signal boost (max +30%)
    raw = {s: BASE[s] + signals.get(s, 0.0) * 0.3 for s in BASE}

    # Apply hard caps
    capped = {s: float(np.clip(raw[s], *CAPS[s])) for s in raw}

    # Normalize → total = 1.0
    total = sum(capped.values())
    weights = {s: v / total for s, v in capped.items()} if total > 0 else BASE.copy()

    if verbose:
        print("  ⚖️  Dynamic Weights:")
        for s, w in weights.items():
            if w > 0:
                print(f"     {s:<15} {w:.1%}  {'█' * int(w * 40)}")
        print(f"     {'TOTAL':<15} {sum(weights.values()):.1%}")

    return weights


print("\n✅ SBERT Encoder & Dynamic Weighting ready!")
print("   4A — encode_text(), encode_sections(), encode_jd(), section_similarity()")
print("   4B — compute_dynamic_weights()")

# ============================================================
# CELL 5: HYBRID SCORER + RANKER
#   5A — Hybrid Scorer (section-weighted + full-text)
#   5B — Batch Ranker
# ============================================================


# ── 5A: HYBRID SCORER ────────────────────────────────────────

def score_cv(
    cv_text: str,
    jd_text: str,
    jd_embedding:     Optional[np.ndarray] = None,
    dynamic_weights:  Optional[Dict]        = None,
    hybrid_alpha:     float                 = 0.7,
) -> Dict:
    """
    Score satu CV terhadap satu JD menggunakan hybrid scoring.

    Formula:
        final = (section_weighted_score × alpha) + (fulltext_score × (1−alpha))

    Fallback:
        Jika CV flat (< 2 section terdeteksi) → fulltext 100%
        Ini memastikan CV tanpa heading tetap mendapat score yang fair.

    Args:
        cv_text         : full teks CV (sudah di-clean)
        jd_text         : full teks JD
        jd_embedding    : pre-computed JD embedding (opsional, efisiensi batch)
        dynamic_weights : pre-computed weights (opsional, efisiensi batch)
        hybrid_alpha    : bobot section score (default 0.7)

    Returns:
        Dict berisi:
            final_score     : float 0–100 (score akhir)
            section_score   : float 0–100 (komponen section-weighted)
            fulltext_score  : float 0–100 (komponen full-text)
            scoring_mode    : 'hybrid' | 'fulltext_fallback'
            section_scores  : Dict per-section score (0–100)
            weights_used    : Dict bobot yang digunakan
            non_empty_sections : int jumlah section yang terdeteksi
    """
    # Pastikan weights & embedding tersedia
    if dynamic_weights is None:
        dynamic_weights = compute_dynamic_weights(jd_text)
    if jd_embedding is None:
        jd_embedding = encode_jd(jd_text)

    # ── Komponen 1: Section-weighted score ──
    cv_sections   = extract_cv_sections(cv_text)
    cv_embeddings = encode_sections(cv_sections)

    section_scores  = {}
    weighted_total  = 0.0
    active_weight   = 0.0

    for sec, weight in dynamic_weights.items():
        if weight == 0.0:
            section_scores[sec] = 0.0
            continue

        sim = section_similarity(cv_embeddings.get(sec), jd_embedding)
        section_scores[sec] = round(sim * 100, 2)

        if cv_embeddings.get(sec) is not None:
            weighted_total += sim * weight
            active_weight  += weight

    section_score = (weighted_total / active_weight * 100) if active_weight > 0 else 0.0

    # ── Komponen 2: Full-text score ──
    fulltext_emb   = encode_text(clean_text_for_sbert(cv_text))
    fulltext_score = section_similarity(fulltext_emb, jd_embedding) * 100

    # ── Hybrid combination ──
    non_empty = sum(1 for v in cv_sections.values() if v and len(v) > 20)

    if non_empty >= 2:
        final = section_score * hybrid_alpha + fulltext_score * (1 - hybrid_alpha)
        mode  = 'hybrid'
    else:
        final = fulltext_score
        mode  = 'fulltext_fallback'

    return {
        'final_score':        round(float(np.clip(final, 0.0, 100.0)), 2),
        'section_score':      round(section_score, 2),
        'fulltext_score':     round(fulltext_score, 2),
        'scoring_mode':       mode,
        'section_scores':     section_scores,
        'section_texts':      cv_sections,
        'weights_used':       dynamic_weights,
        'non_empty_sections': non_empty,
    }


# ── 5B: BATCH RANKER ─────────────────────────────────────────

def rank_cvs(
    cv_list:       List[Dict],
    jd_text:       str,
    top_n:         Optional[int] = None,
    hybrid_alpha:  float         = 0.7,
    show_progress: bool          = True,
) -> List[Dict]:
    """
    Rank banyak CV terhadap satu JD.

    Efisiensi batch:
        - JD di-encode SEKALI
        - Dynamic weights dihitung SEKALI
        - Semua CV pakai embedding & weights yang sama

    Args:
        cv_list       : List of Dict, tiap item wajib punya key:
                            'id'   : identifier CV
                            'text' : teks CV
                        Key lain (category, name, dll) dipertahankan di output.
        jd_text       : full teks JD
        top_n         : ambil N teratas saja (None = semua)
        hybrid_alpha  : bobot section score (default 0.7)
        show_progress : tampilkan progress bar tqdm

    Returns:
        List of Dict sorted by final_score descending.
        Setiap item = data CV original + hasil scoring + 'rank'.
    """
    print("  📊 Analyzing JD...")
    weights      = compute_dynamic_weights(jd_text)
    jd_embedding = encode_jd(jd_text)

    results  = []
    iterator = tqdm(cv_list, desc="Scoring CVs") if show_progress else cv_list

    for cv_data in iterator:
        cv_text = cv_data.get('text', '')
        if not cv_text:
            continue

        scored = score_cv(
            cv_text, jd_text,
            jd_embedding    = jd_embedding,
            dynamic_weights = weights,
            hybrid_alpha    = hybrid_alpha,
        )
        results.append({**cv_data, **scored})

    results.sort(key=lambda x: x['final_score'], reverse=True)

    for i, r in enumerate(results):
        r['rank'] = i + 1

    return results[:top_n] if top_n else results


print("✅ Hybrid Scorer & Ranker ready!")
print("   5A — score_cv()")
print("   5B — rank_cvs()")

# ============================================================
# CELL 6: RANKING REPORT + PUBLIC API
#   6A — Match Label & Reasoning
#   6B — Laporan Teks (HRD-friendly)
#   6C — Public API (entry point untuk Flask)
# ============================================================


# ── 6A: MATCH LABEL & REASONING ──────────────────────────────

def get_match_label(score: float) -> Tuple[str, str]:
    """
    Konversi score numerik ke label match.

    Returns:
        Tuple (label_text, emoji)
        Contoh: ('Strong Match', '🟢')
    """
    if score >= MATCH_THRESHOLDS['strong']:
        return MATCH_LABELS['strong']
    elif score >= MATCH_THRESHOLDS['potential']:
        return MATCH_LABELS['potential']
    return MATCH_LABELS['low']


def generate_reasoning(score_result: Dict) -> str:
    """
    Generate reasoning singkat (1–2 kalimat) untuk HRD.

    Logika:
        - Identifikasi section terkuat & terlemah
        - Sesuaikan kalimat dengan label match
        - Bantu HRD memahami dasar penilaian AI

    Args:
        score_result: output dari score_cv()

    Returns:
        str: reasoning natural dalam Bahasa Indonesia
    """
    section_scores = score_result.get('section_scores', {})
    weights        = score_result.get('weights_used', SECTION_WEIGHTS_BASE)
    final_score    = score_result.get('final_score', 0)

    active = {
        k: v for k, v in section_scores.items()
        if weights.get(k, 0) > 0 and v > 0
    }

    if not active:
        return "Tidak cukup konten CV untuk dianalisis."

    strongest       = max(active, key=active.get)
    weakest         = min(active, key=active.get)
    strongest_score = active[strongest]
    weakest_score   = active[weakest]

    SECTION_ID = {
        'experience': 'pengalaman kerja',   'skills': 'keahlian teknis',
        'summary':    'profil kandidat',    'education': 'latar belakang pendidikan',
        'certifications': 'sertifikasi',
    }

    s_label = SECTION_ID.get(strongest, strongest)
    w_label = SECTION_ID.get(weakest, weakest)

    if final_score >= MATCH_THRESHOLDS['strong']:
        reasoning = f"Kandidat menunjukkan relevansi tinggi pada bagian {s_label} ({strongest_score:.0f}%)."
        if weakest_score < 35 and weakest != strongest:
            reasoning += f" Bagian {w_label} relatif kurang relevan ({weakest_score:.0f}%) — perlu eksplorasi saat interview."
    elif final_score >= MATCH_THRESHOLDS['potential']:
        reasoning = (
            f"Kandidat memiliki potensi di bagian {s_label} ({strongest_score:.0f}%), "
            f"namun bagian {w_label} perlu digali lebih lanjut saat interview."
        )
    else:
        reasoning = "Profil kandidat kurang sesuai dengan kebutuhan posisi ini."
        if strongest_score > 30:
            reasoning += f" Relevansi hanya terdeteksi pada bagian {s_label} ({strongest_score:.0f}%)."

    return reasoning


# ── 6B: LAPORAN TEKS ─────────────────────────────────────────

def build_report(
    ranked_results:     List[Dict],
    jd_title:           str  = "Posisi yang Dilamar",
    top_n:              Optional[int] = None,
    show_section_detail: bool = False,
) -> str:
    """
    Format hasil ranking menjadi laporan teks yang HRD-friendly.

    Args:
        ranked_results      : output dari rank_cvs()
        jd_title            : nama posisi untuk header laporan
        top_n               : tampilkan N kandidat teratas (None = semua)
        show_section_detail : tampilkan per-section score

    Returns:
        str: laporan ranking siap cetak / kirim ke frontend
    """
    to_show = ranked_results[:top_n] if top_n else ranked_results
    total   = len(ranked_results)

    strong    = sum(1 for r in ranked_results if r['final_score'] >= MATCH_THRESHOLDS['strong'])
    potential = sum(1 for r in ranked_results
                    if MATCH_THRESHOLDS['potential'] <= r['final_score'] < MATCH_THRESHOLDS['strong'])
    low       = total - strong - potential

    SEP  = "=" * 68
    SEP2 = "-" * 68

    lines = [
        SEP,
        f"  LAPORAN RANKING CV — {jd_title.upper()}",
        f"  {datetime.now().strftime('%d %B %Y, %H:%M')}",
        SEP,
        f"  Total kandidat   : {total}",
        f"  🟢 Strong Match   : {strong}",
        f"  🟡 Potential Match: {potential}",
        f"  🔴 Low Match      : {low}",
    ]

    if top_n and top_n < total:
        lines.append(f"\n  Menampilkan {top_n} dari {total} kandidat:")

    lines.append(SEP2)

    for r in to_show:
        label, emoji = get_match_label(r['final_score'])
        lines += [
            f"\n  Rank #{r['rank']}  {emoji} {label}",
            f"  ID       : {r.get('id', f'Kandidat #{r["rank"]}')}",
        ]
        if r.get('category'):
            lines.append(f"  Kategori : {r['category']}")
        lines.append(f"  Score    : {r['final_score']:.1f}%")
        lines.append(f"  Analisis : {generate_reasoning(r)}")

        if show_section_detail:
            weights = r.get('weights_used', {})
            active  = {k: v for k, v in r['section_scores'].items()
                       if weights.get(k, 0) > 0 and v > 0}
            if active:
                lines.append("  Detail   :")
                for sec, sc in sorted(active.items(), key=lambda x: x[1], reverse=True):
                    w   = weights.get(sec, 0)
                    bar = '█' * int(sc / 10)
                    lines.append(f"    {sec:<15} {sc:>5.1f}%  {bar}  (bobot {w:.0%})")

        lines.append("  " + SEP2)

    lines += [
        "\n  ⚠️  DISCLAIMER",
        "  Score adalah indikator relevansi semantik berbasis AI.",
        "  Sistem ini adalah alat bantu penyaringan — bukan pengambil keputusan.",
        "  Keputusan rekrutmen final sepenuhnya ada di tangan HRD.",
        SEP,
    ]

    return '\n'.join(lines)


# ── 6C: PUBLIC API ───────────────────────────────────────────
# Fungsi-fungsi inilah yang dipanggil dari Flask / frontend

def analyze_single(cv_input: str, jd_text: str, jd_title: str = "Posisi") -> Dict:
    """
    Analisis satu CV terhadap satu JD.
    Digunakan untuk fitur Job Seeker (upload 1 CV).

    Args:
        cv_input : path PDF atau teks CV langsung
        jd_text  : full teks JD
        jd_title : nama posisi (untuk laporan)

    Returns:
        Dict berisi:
            score_result : output score_cv() lengkap
            label        : Tuple (label_text, emoji)
            reasoning    : str reasoning untuk kandidat
            report       : str laporan teks lengkap
    """
    cv_text      = load_cv(cv_input)
    score_result = score_cv(cv_text, jd_text)
    label        = get_match_label(score_result['final_score'])
    reasoning    = generate_reasoning(score_result)

    report = build_report(
        ranked_results=[{**score_result, 'id': 'Kandidat', 'rank': 1}],
        jd_title=jd_title,
        show_section_detail=True,
    )

    return {
        'score_result': score_result,
        'label':        label,
        'reasoning':    reasoning,
        'report':       report,
    }


def analyze_batch(
    cv_inputs:  List[Dict],
    jd_text:    str,
    jd_title:   str           = "Posisi",
    top_n:      Optional[int] = None,
    show_detail: bool         = False,
) -> Dict:
    """
    Ranking banyak CV terhadap satu JD.
    Digunakan untuk fitur HRD (upload multiple CV).

    Args:
        cv_inputs  : List of Dict dengan key:
                        'id'    : nama file / identifier
                        'text'  : teks CV (sudah di-load)
                     Atau langsung dari load_cv() per item.
        jd_text    : full teks JD
        jd_title   : nama posisi
        top_n      : tampilkan N teratas di laporan
        show_detail: tampilkan per-section score di laporan

    Returns:
        Dict berisi:
            ranked  : List hasil ranking lengkap
            report  : str laporan teks
            summary : Dict statistik (total, strong, potential, low)
    """
    ranked = rank_cvs(cv_inputs, jd_text, top_n=None)

    report = build_report(
        ranked_results=ranked,
        jd_title=jd_title,
        top_n=top_n,
        show_section_detail=show_detail,
    )

    total     = len(ranked)
    strong    = sum(1 for r in ranked if r['final_score'] >= MATCH_THRESHOLDS['strong'])
    potential = sum(1 for r in ranked
                    if MATCH_THRESHOLDS['potential'] <= r['final_score'] < MATCH_THRESHOLDS['strong'])

    return {
        'ranked':  ranked,
        'report':  report,
        'summary': {
            'total':     total,
            'strong':    strong,
            'potential': potential,
            'low':       total - strong - potential,
        },
    }


print("✅ Public API ready!")
print("   6A — get_match_label(), generate_reasoning()")
print("   6B — build_report()")
print("   6C — analyze_single()  ← untuk Job Seeker (1 CV)")
print("        analyze_batch()   ← untuk HRD (multiple CV)")

# ============================================================
# QUICK SMOKE TEST
# Jalankan ini setelah semua cell di atas untuk verifikasi
# ============================================================

print("\n" + "=" * 68)
print("SMOKE TEST — VERIFIKASI PIPELINE")
print("=" * 68)

_sample_jd = """
We are looking for a Data Scientist with minimum 3 years experience.
Requirements:
- Python, R, SQL, machine learning, data analysis
- TensorFlow, PyTorch, or Scikit-learn
- Statistical modeling and data visualization
- Bachelor's degree in Computer Science or Statistics
"""

_sample_cv = """
JOHN DOE | john@email.com

Summary
Data Scientist with 4 years of experience in machine learning and analytics.
Proficient in Python, SQL, and statistical modeling.

Work Experience
Data Scientist | Tech Corp | 2020 – Present
- Built ML models using Scikit-learn and TensorFlow
- Conducted data analysis and visualization for business insights
- 4 years hands-on experience in data science projects

Skills
Python, R, SQL, TensorFlow, Scikit-learn, Data Visualization, Statistics

Education
Bachelor of Science in Computer Science | 2020
"""

# Test single
result = analyze_single(_sample_cv, _sample_jd, "Data Scientist")
label, emoji = result['label']
print(f"\n  analyze_single() → {emoji} {label} ({result['score_result']['final_score']:.1f}%)")
print(f"  Reasoning: {result['reasoning']}")

# Test batch
_batch = [
    {'id': 'john_data_scientist', 'text': _sample_cv},
    {'id': 'random_accountant',   'text': "Senior Accountant with 8 years in finance, audit, and taxation. Excel, SAP, financial reporting."},
]
batch_result = analyze_batch(_batch, _sample_jd, "Data Scientist", show_detail=False)
print(f"\n  analyze_batch()  → {batch_result['summary']}")
for r in batch_result['ranked']:
    lbl, em = get_match_label(r['final_score'])
    print(f"    #{r['rank']} {em} {r['id']:<30} {r['final_score']:.1f}%")

print("\n✅ Smoke test passed — pipeline siap digunakan!")
print("=" * 68)
print("""
ENTRY POINTS UNTUK FLASK:
  from cv_matcher_final import analyze_single, analyze_batch, load_cv

  # Job Seeker (1 CV)
  result = analyze_single(cv_pdf_path, jd_text, jd_title)

  # HRD (multiple CV)
  cv_list = [{'id': f.name, 'text': load_cv(str(f))} for f in pdf_files]
  result  = analyze_batch(cv_list, jd_text, jd_title, top_n=10)
""")